apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migrations-{{ .Release.Revision }}
spec:
  template:
    metadata:
      name: migration
    spec:
      containers:
        - name: sleep
          image: debian:10-slim
          command: ["/bin/sh", "-c"]
          args: ["sleep 20"]
      restartPolicy: Never
